packadd minpac
call minpac#init()

" feature
call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-fugitive')
call minpac#add('airblade/vim-gitgutter')
call minpac#add('scrooloose/nerdtree')
call minpac#add('kien/ctrlp.vim')
call minpac#add('mattn/emmet-vim')
call minpac#add('SirVer/ultisnips')
call minpac#add('zirrostig/vim-schlepp')
call minpac#add('prettier/vim-prettier')
call minpac#add('scrooloose/nerdcommenter')
call minpac#add('jiangmiao/auto-pairs')
call minpac#add('Valloric/YouCompleteMe')
" call minpac#add('w0rp/ale')
call minpac#add('terryma/vim-multiple-cursors')
call minpac#add('christoomey/vim-tmux-navigator')
call minpac#add('christoomey/vim-sort-motion')

" visual
call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
call minpac#add('ap/vim-css-color')
call minpac#add('Yggdroot/indentLine')
call minpac#add('MaxMEllon/vim-jsx-pretty')
call minpac#add('tomasiser/vim-code-dark')
call minpac#add('jparise/vim-graphql')
call minpac#add('elzr/vim-json')

" javascript
call minpac#add('pangloss/vim-javascript')
call minpac#add('mxw/vim-jsx')

" theme
colorscheme codedark

let mapleader = "\<Space>"
let &t_Co=256
map <leader>h :nohlsearch<CR>
map sgf <C-W>f
map vgf <C-W>vgf
map gF <C-W>gf
map <C-T> :tabnew<CR>
set nocompatible
set number
set backspace=2
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set smartindent
set ai
set ignorecase
set smartcase
set incsearch
set encoding=utf8
set nobackup
set noswapfile
set nowb
set history=1000
set hlsearch
set timeoutlen=1000 ttimeoutlen=0
set clipboard=unnamed
set nocursorcolumn
set nocursorline
set norelativenumber
set lazyredraw
set ttyfast
filetype indent on
filetype plugin on
syntax sync minlines=256
syntax on

" mxw/vim-jsx
let g:jsx_ext_required = 0

" zirrostig/vim-schlepp
vmap <unique> <C-h> <Plug>SchleppLeft
vmap <unique> <C-l> <Plug>SchleppRight
vmap <unique> <C-j> <Plug>SchleppDown
vmap <unique> <C-k> <Plug>SchleppUp

" scrooloose/nerdtree
map <C-\> :NERDTreeToggle<CR>

" kien/ctrlp.vim
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|.git|.meteor'
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" prettier/vim-prettier
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#jsx_bracket_same_line = 'false'

" terryma/vim-multiple-cursors
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

" SirVer/ultisnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"]

" christoomey/vim-tmux-navigator
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-J> :TmuxNavigateDown<cr>
nnoremap <silent> <C-K> :TmuxNavigateUp<cr>
nnoremap <silent> <C-L> :TmuxNavigateRight<cr>
nnoremap <silent> <C-H> :TmuxNavigateLeft<cr>

" w0rp/ale
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
let g:ale_fixers = {
\   'javascript': ['eslint'],
\}
let g:ale_sign_error = '>'
let g:ale_sign_warning = '-'
highlight clear ALEErrorSign
highlight clear ALEWarningSign

" vim-airline/vim-airline
" let g:airline_theme = 'simple'
let g:airline_extensions = []

" airblade/vim-gitgutter
highlight SignColumn ctermbg=black
let g:gitgutter_override_sign_column_highlight = 0
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '~'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '-'
let g:gitgutter_sign_modified_removed = '-'
let g:gitgutter_realtime = 0
let g:gitgutter_eager = 0

" scrooloose/nerdcommenter
let g:NERDAltDelims_javascript = 1
let g:NERDCustomDelimiters = { 'javascript': { 'left': '//', 'leftAlt': '{/*','rightAlt': '*/}' } }
let g:NERDSpaceDelims = 1

" elzr/vim-json
let g:vim_json_syntax_conceal = 0

