source ~/.zsh/plugins/antigen.zsh
source ~/.zshrc-custom

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting

PROMPT="$ "

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/Library/Python/3.7/lib/python/site-packages"
